import { BlockerImpact, BlockerStatus, BlockerType } from "@/enums";
import type { BlockerInterface } from "@/interfaces";

export const seedBlockers: BlockerInterface[] = [
    {
        id: "blk-001", title: "Dashboard metrics API not ready",
        description: "The backend API for aggregated sprint metrics is still in development. Frontend dashboard widgets cannot display real-time data.",
        type: BlockerType.ApiDependency, status: BlockerStatus.Active, impact: BlockerImpact.Critical,
        reporterId: "usr-001", ownerId: "usr-003", taskIds: ["tsk-007"], sprintId: "spr-014",
        createdAt: "2026-03-28", durationDays: 7, notes: "Ahmed Heikal estimating 2 more days. Using mock data as workaround.",
    },
    {
        id: "blk-002", title: "Decision log data model not finalized",
        description: "Product has not confirmed the final fields for the decision log entries. Pending approval from Karim (PM).",
        type: BlockerType.Requirements, status: BlockerStatus.Active, impact: BlockerImpact.High,
        reporterId: "usr-004", ownerId: "usr-008", taskIds: ["tsk-012"], sprintId: "spr-014",
        createdAt: "2026-03-30", durationDays: 5, notes: "Meeting scheduled for tomorrow with Karim to finalize.",
    },
    {
        id: "blk-003", title: "Database schema migration pending",
        description: "The metrics aggregation endpoint needs a new database table that has not been migrated yet in staging.",
        type: BlockerType.Technical, status: BlockerStatus.Active, impact: BlockerImpact.High,
        reporterId: "usr-003", ownerId: "usr-003", taskIds: ["tsk-009"], sprintId: "spr-014",
        createdAt: "2026-04-01", durationDays: 3, notes: "DevOps ticket created. Waiting for staging access approval from Hazem.",
    },
    {
        id: "blk-004", title: "QA environment not configured for analytics",
        description: "The QA environment is missing the seed data needed to test multi-sprint analytics comparisons.",
        type: BlockerType.QAHandoff, status: BlockerStatus.Active, impact: BlockerImpact.Medium,
        reporterId: "usr-009", ownerId: "usr-009", taskIds: ["tsk-016"], sprintId: "spr-014",
        createdAt: "2026-04-02", durationDays: 2, notes: "Rashad will set up test data by end of day.",
    },
    {
        id: "blk-005", title: "Report page design not approved",
        description: "Mohamed Ahmed (UI/UX) has not provided the final mockups for the executive report layout.",
        type: BlockerType.Design, status: BlockerStatus.Resolved, impact: BlockerImpact.Medium,
        reporterId: "usr-001", ownerId: "usr-012", taskIds: ["tsk-005"], sprintId: "spr-014",
        createdAt: "2026-03-25", resolvedAt: "2026-03-28", durationDays: 3, notes: "Design approved. Using card-style layout.",
    },
    {
        id: "blk-006", title: "Unclear requirements for workload capacity calculation",
        description: "Karim (PM) did not specify how to calculate team member capacity. Multiple formulas were suggested but no decision was made.",
        type: BlockerType.Requirements, status: BlockerStatus.Resolved, impact: BlockerImpact.High,
        reporterId: "usr-002", ownerId: "usr-008", taskIds: ["tsk-013"], sprintId: "spr-014",
        createdAt: "2026-03-26", resolvedAt: "2026-03-30", durationDays: 4, notes: "Resolved: Using story points per sprint as capacity metric.",
    },
    {
        id: "blk-007", title: "Cross-team auth token sharing issue",
        description: "Backend auth tokens generated by Ahmed Heikal's auth service are not being properly forwarded to the metrics service.",
        type: BlockerType.ApiDependency, status: BlockerStatus.Resolved, impact: BlockerImpact.Critical,
        reporterId: "usr-001", ownerId: "usr-003", taskIds: ["tsk-018"], sprintId: "spr-014",
        createdAt: "2026-03-24", resolvedAt: "2026-03-26", durationDays: 2, notes: "Fixed: Token forwarding header was misconfigured.",
    },
    {
        id: "blk-008", title: "Missing communication SLA definition",
        description: "No one has defined what counts as acceptable response time for communication tracking SLAs. Needs leadership input.",
        type: BlockerType.Communication, status: BlockerStatus.Escalated, impact: BlockerImpact.Medium,
        reporterId: "usr-001", ownerId: "usr-005", taskIds: ["tsk-014"], sprintId: "spr-014",
        createdAt: "2026-03-29", durationDays: 6, notes: "Escalated to Hazem (CTO). Need org-wide SLA policy.",
    },
    {
        id: "blk-009", title: "Settings page API contract changed mid-sprint",
        description: "Ahmed Bashier changed the settings API response format after Mohamed Elhawary started frontend implementation, requiring rework.",
        type: BlockerType.Requirements, status: BlockerStatus.Resolved, impact: BlockerImpact.High,
        reporterId: "usr-001", ownerId: "usr-004", taskIds: ["tsk-004"], sprintId: "spr-014",
        createdAt: "2026-03-27", resolvedAt: "2026-03-31", durationDays: 4, notes: "API contract documented and frozen. Frontend adapter pattern applied.",
    },
];
