import { TaskPhase, TaskPriority } from "@/enums";
import type { ReadinessChecklistInterface } from "@/interfaces";

export const tasksConstants = {
    columns: [
        { phase: TaskPhase.Backlog, label: "Backlog", index: 0 },
        { phase: TaskPhase.Ready, label: "Ready", index: 1 },
        { phase: TaskPhase.InProgress, label: "In Progress", index: 2 },
        { phase: TaskPhase.Review, label: "Review", index: 3 },
        { phase: TaskPhase.QA, label: "QA", index: 4 },
        { phase: TaskPhase.Done, label: "Done", index: 5 },
    ] as { phase: TaskPhase; label: string; index: number }[],
    phaseIndex: {
        [TaskPhase.Backlog]: 0,
        [TaskPhase.Ready]: 1,
        [TaskPhase.InProgress]: 2,
        [TaskPhase.Review]: 3,
        [TaskPhase.QA]: 4,
        [TaskPhase.Done]: 5,
    } as Record<TaskPhase, number>,
    priorityVariants: {
        [TaskPriority.Critical]: "error",
        [TaskPriority.High]: "warning",
        [TaskPriority.Medium]: "default",
        [TaskPriority.Low]: "secondary",
    } as Record<TaskPriority, "error" | "warning" | "default" | "secondary">,
    readinessLabels: [
        { key: "acceptanceCriteriaDefined", label: "Acceptance criteria defined" },
        { key: "businessRulesClear", label: "Business rules clear" },
        { key: "edgeCasesIdentified", label: "Edge cases identified" },
        { key: "dependenciesMapped", label: "Dependencies mapped" },
        { key: "designAvailable", label: "Design available" },
        { key: "apiContractReady", label: "API contract ready" },
        { key: "estimationDone", label: "Estimation done" },
    ] as { key: keyof ReadinessChecklistInterface; label: string }[],
    columnColors: {
        [TaskPhase.Backlog]: "bg-text-muted",
        [TaskPhase.Ready]: "bg-primary",
        [TaskPhase.InProgress]: "bg-warning",
        [TaskPhase.Review]: "bg-[#8b5cf6]",
        [TaskPhase.QA]: "bg-[#ec4899]",
        [TaskPhase.Done]: "bg-success",
    } as Record<TaskPhase, string>,
    readinessThreshold: 70,
    searchDebounceMs: 400,
    defaultFilters: { status: "all", priority: "all", assignee: "all", type: "all" },
    statusFilterOptions: [
        { value: "all", label: "All Statuses" },
        { value: "backlog", label: "Backlog" },
        { value: "ready", label: "Ready" },
        { value: "in_progress", label: "In Progress" },
        { value: "review", label: "Review" },
        { value: "qa", label: "QA" },
        { value: "done", label: "Done" },
        { value: "blocked", label: "Blocked" },
    ],
    priorityFilterOptions: [
        { value: "all", label: "All Priorities" },
        { value: TaskPriority.Low, label: "Low" },
        { value: TaskPriority.Medium, label: "Medium" },
        { value: TaskPriority.High, label: "High" },
        { value: TaskPriority.Critical, label: "Critical" },
    ],
    typeFilterOptions: [
        { value: "all", label: "All Types" },
        { value: "feature", label: "Feature" },
        { value: "bug", label: "Bug" },
    ],
    deleteConfirmTitle: "Delete Task",
    mentionMaxResults: 8,
    pipelineColumnColorClass: {
        backlog: "text-slate-400",
        ready: "text-primary",
        in_progress: "text-warning",
        review: "text-purple-500",
        qa: "text-pink-500",
        done: "text-success",
    } as Record<string, string>,
    errors: {
        fetchFailed: "Failed to load tasks.",
        createFailed: "Failed to create task.",
        updateFailed: "Failed to update task.",
        deleteFailed: "Failed to delete task.",
        attachmentUploadFailed: "Failed to upload attachment.",
        attachmentDeleteFailed: "Failed to delete attachment.",
        tagAddFailed: "Failed to add tag.",
        tagRemoveFailed: "Failed to remove tag.",
        commentAddFailed: "Failed to add comment.",
        commentUpdateFailed: "Failed to update comment.",
        commentDeleteFailed: "Failed to delete comment.",
        markCompleteFailed: "Failed to send for approval.",
    },
    messages: {
        createSuccess: "Task created.",
        updateSuccess: "Task updated.",
        deleteSuccess: "Task deleted.",
        attachmentUploadSuccess: "Attachment uploaded.",
        attachmentDeleteSuccess: "Attachment deleted.",
        tagAddSuccess: "Tag added.",
        tagRemoveSuccess: "Tag removed.",
        commentAddSuccess: "Comment added.",
        commentUpdateSuccess: "Comment updated.",
        commentDeleteSuccess: "Comment deleted.",
        markCompleteSuccess: "Sent for manager approval.",
    },
};
