import { getStorageItem } from "./storage";

const SETTINGS_KEY = "twindix_perf_settings";

const getLang = (): "en" | "ar" => {
    const s = getStorageItem<{ language?: string }>(SETTINGS_KEY);
    return (s?.language as "en" | "ar") ?? "en";
};

const ar: Record<string, string> = {
    // Metric names
    "Task Readiness Rate": "معدل جاهزية المهام",
    "Clarification Waiting Time": "وقت انتظار التوضيح",
    "Blocked Task Count": "عدد المهام المحظورة",
    "Requirement Leakage Rate": "معدل تسرب المتطلبات",
    "Rework Percentage": "نسبة إعادة العمل",
    "Communication Response Time": "وقت استجابة التواصل",
    "Cross-Team Dependency Delay": "تأخير التبعيات بين الفرق",
    "Story Quality Score": "مؤشر جودة القصة",
    "Ownership Conflict Count": "عدد تعارضات الملكية",
    "Bug Source: Shortcuts": "مصدر الأخطاء: الاختصارات",
    "Handoff Completion Rate": "معدل إنجاز التسليمات",
    "Decision Log Coverage": "تغطية سجل القرارات",
    "Context Switching Frequency": "تكرار تبديل السياق",
    "Workload Balance": "توازن عبء العمل",
    "Onboarding & Turnover Cost": "تكلفة التأهيل ودوران الموظفين",
    "Unreviewed Shared Changes": "تغييرات مشتركة غير مراجعة",
    "Vibe-Coding Incidents": "حوادث البرمجة العشوائية",

    // Metric descriptions (Sprint 14)
    "Close to target at 71%. Readiness gate catching incomplete tasks before they start": "قريب من الهدف عند 71%. بوابة الجاهزية تلتقط المهام غير المكتملة قبل بدئها",
    "Continued improvement to 4.1 hours. Still above 2-hour target": "تحسن مستمر إلى 4.1 ساعة. لا يزال أعلى من هدف الساعتين",
    "4 active blockers this sprint. API dependencies remain the top blocker type": "4 عوائق نشطة في هذا السبرنت. تبعيات API لا تزال النوع الأكثر عرقلة",
    "Down to 18%. Story template catching more gaps upfront": "انخفض إلى 18%. قالب القصة يلتقط المزيد من الثغرات مسبقاً",
    "15% rework, approaching target. Mostly from mid-sprint requirement changes": "15% إعادة عمل، يقترب من الهدف. معظمها من تغييرات المتطلبات منتصف السبرنت",
    "Nearly at target. Structured blocker tracking proving effective": "قريب من الهدف. تتبع العوائق المنظم يثبت فعاليته",
    "Significantly improved. Early dependency flagging working well": "تحسن ملحوظ. الإبلاغ المبكر عن التبعيات يعمل بشكل جيد",
    "Story quality at 74, nearing the 80-point target": "جودة القصة عند 74، تقترب من هدف 80 نقطة",
    "Only 3 conflicts this sprint. Named owners reducing confusion": "3 تعارضات فقط في هذا السبرنت. المالكون المحددون يقللون الارتباك",
    "Architecture notes requirement cutting shortcut-related bugs significantly": "متطلب ملاحظات الهيكلة يقلل أخطاء الاختصارات بشكل كبير",
    "Strong improvement to 78%. Standardized checklists becoming team habit": "تحسن قوي إلى 78%. القوائم المعيارية تصبح عادة للفريق",
    "70% of decisions now documented. Team adopting decision log as habit": "70% من القرارات موثقة الآن. الفريق يتبنى سجل القرارات كعادة",
    "Near target at 2.8. Workload rebalancing helping focus": "قريب من الهدف عند 2.8. إعادة توازن العمل تساعد في التركيز",
    "Nearly balanced workload. Only minor adjustments needed": "عبء عمل شبه متوازن. تعديلات طفيفة فقط مطلوبة",
    "Lower turnover cost. Better documentation reducing re-handover effort": "تكلفة دوران أقل. التوثيق الأفضل يقلل جهد إعادة التسليم",
    "Continued improvement. Review gates catching most unauthorized changes": "تحسن مستمر. بوابات المراجعة تلتقط معظم التغييرات غير المصرح بها",
    "Near target. Architecture-first culture taking hold": "قريب من الهدف. ثقافة الهيكلة أولاً تترسخ",

    // Metric descriptions (Sprint 12 & 13)
    "Only 45% of tasks had complete requirements before starting development": "45% فقط من المهام كانت لديها متطلبات كاملة قبل بدء التطوير",
    "Team lost an average of 8.5 hours per question waiting for clarification": "الفريق خسر متوسط 8.5 ساعة لكل سؤال في انتظار التوضيح",
    "9 tasks were blocked during the sprint, severely impacting delivery": "9 مهام تم حظرها خلال السبرنت، مما أثر بشدة على التسليم",
    "35% of tasks had missing requirements discovered after development started": "35% من المهام اكتُشفت فيها متطلبات ناقصة بعد بدء التطوير",
    "28% of completed work had to be redone due to changing requirements or unclear direction": "28% من العمل المكتمل أُعيد بسبب تغيير المتطلبات أو عدم وضوح الاتجاه",
    "Average 12-hour wait for critical answers across all channels": "انتظار 12 ساعة في المتوسط للإجابات الحرجة عبر جميع القنوات",
    "Average 4.2 days of delay per cross-team dependency": "متوسط 4.2 يوم تأخير لكل تبعية بين الفرق",
    "Low story quality due to missing edge cases and incomplete acceptance criteria": "جودة قصة منخفضة بسبب حالات حدية مفقودة ومعايير قبول غير مكتملة",
    "7 cases of unclear ownership causing duplicated work or regressions": "7 حالات ملكية غير واضحة تسببت في عمل مكرر أو انحدار",
    "65% of bugs traced back to hasty implementations and missing edge-case handling": "65% من الأخطاء تعود إلى تطبيقات متسرعة ومعالجة حالات حدية مفقودة",
    "Only 40% of phase transitions met all entry and exit criteria": "40% فقط من انتقالات المراحل استوفت جميع معايير الدخول والخروج",
    "70% of key decisions were made verbally without documentation": "70% من القرارات الرئيسية اتُخذت شفهياً بدون توثيق",
    "Team members switched between 4.5 unrelated tasks per day on average": "أعضاء الفريق تنقلوا بين 4.5 مهمة غير مرتبطة يومياً في المتوسط",
    "Highly unbalanced: some members at 150% capacity while others at 60%": "غير متوازن بشدة: بعض الأعضاء عند 150% سعة والبعض عند 60%",
    "$15K spent on re-handover and knowledge transfer due to team changes": "15 ألف دولار أُنفقت على إعادة التسليم ونقل المعرفة بسبب تغييرات الفريق",
    "18 changes to shared components shipped without owner review": "18 تغييراً على المكونات المشتركة تم شحنها بدون مراجعة المالك",
    "11 implementations flagged for missing architecture notes or shortcut patterns": "11 تطبيقاً تم الإبلاغ عنها لعدم وجود ملاحظات هيكلة أو أنماط اختصار",

    "Improved to 62% with introduction of readiness checklist": "تحسن إلى 62% مع تقديم قائمة فحص الجاهزية",
    "Reduced to 5.2 hours after setting response time expectations": "انخفض إلى 5.2 ساعة بعد تحديد توقعات وقت الاستجابة",
    "Down to 6 blocked tasks with better dependency visibility": "انخفض إلى 6 مهام محظورة مع رؤية أفضل للتبعيات",
    "Leakage reduced to 22% with improved story templates": "انخفض التسرب إلى 22% مع تحسين قوالب القصص",
    "Rework dropped to 19% after stricter acceptance criteria enforcement": "انخفض إعادة العمل إلى 19% بعد فرض أكثر صرامة لمعايير القبول",
    "Response time cut in half with structured blocker tracking": "وقت الاستجابة انخفض للنصف مع تتبع العوائق المنظم",
    "Delay reduced to 2.8 days with early dependency flagging": "التأخير انخفض إلى 2.8 يوم مع الإبلاغ المبكر عن التبعيات",
    "Improved to 68 with mandatory story template fields": "تحسن إلى 68 مع حقول قالب القصة الإلزامية",
    "Conflicts reduced to 4 after defining shared component owners": "التعارضات انخفضت إلى 4 بعد تحديد مالكي المكونات المشتركة",
    "Shortcut-related bugs dropped to 45% with architecture notes requirement": "أخطاء الاختصارات انخفضت إلى 45% مع متطلب ملاحظات الهيكلة",
    "Handoff quality improved to 65% with standardized checklists": "جودة التسليمات تحسنت إلى 65% مع القوائم المعيارية",
    "More than half of decisions now documented in the decision log": "أكثر من نصف القرارات موثقة الآن في سجل القرارات",
    "Context switching reduced to 3.2 per day with better workload planning": "تبديل السياق انخفض إلى 3.2 يومياً مع تخطيط أفضل للعمل",
    "Better balance: overloaded members reduced from 3 to 1": "توازن أفضل: الأعضاء المحملون زيادة انخفضوا من 3 إلى 1",
    "Reduced onboarding cost with better documentation and handover process": "تكلفة تأهيل أقل مع توثيق أفضل وعملية تسليم محسنة",
    "Halved unreviewed changes with CODEOWNERS and review gates": "التغييرات غير المراجعة انخفضت للنصف مع CODEOWNERS وبوابات المراجعة",
    "Incidents nearly halved after requiring architecture notes for complex tasks": "الحوادث انخفضت تقريباً للنصف بعد طلب ملاحظات الهيكلة للمهام المعقدة",

    // Units
    "hours": "ساعات",
    "tasks": "مهام",
    "days": "أيام",
    "score": "نقطة",
    "K USD": "ألف دولار",
    "conflicts": "تعارضات",
    "changes": "تغييرات",
    "incidents": "حوادث",

    // Handoff criteria
    "Figma designs finalized and approved": "تصاميم Figma منتهية ومعتمدة",
    "Design tokens documented": "رموز التصميم موثقة",
    "Responsive breakpoints specified": "نقاط الاستجابة محددة",
    "Interaction states defined (hover, focus, disabled)": "حالات التفاعل محددة (تحويم، تركيز، معطل)",
    "Accessibility requirements noted": "متطلبات إمكانية الوصول مسجلة",
    "Component structure matches design": "هيكل المكون يطابق التصميم",
    "All states implemented": "جميع الحالات منفذة",
    "Responsive layout verified": "التخطيط المتجاوب تم التحقق منه",
    "All acceptance criteria implemented": "جميع معايير القبول منفذة",
    "Self-review completed": "المراجعة الذاتية مكتملة",
    "No console errors or warnings": "لا أخطاء أو تحذيرات في وحدة التحكم",
    "Edge cases handled": "الحالات الحدية معالجة",
    "Code review approved by 2 reviewers": "مراجعة الكود معتمدة من مراجعَين",
    "Review comments addressed": "تعليقات المراجعة تمت معالجتها",
    "No critical issues remaining": "لا مشاكل حرجة متبقية",
    "PR merged to development branch": "طلب الدمج تم دمجه في فرع التطوير",
    "Test documentation provided": "وثائق الاختبار مقدمة",
    "QA environment updated": "بيئة ضمان الجودة محدثة",
    "Test data available": "بيانات الاختبار متاحة",
    "All test cases passed": "جميع حالات الاختبار نجحت",
    "No critical bugs found": "لا أخطاء حرجة موجودة",
    "Performance acceptable": "الأداء مقبول",
    "User stories written with acceptance criteria": "قصص المستخدم مكتوبة مع معايير القبول",
    "Business rules documented": "قواعد العمل موثقة",
    "User flow defined": "تدفق المستخدم محدد",
    "Edge cases identified": "الحالات الحدية محددة",
    "Priority and timeline confirmed": "الأولوية والجدول الزمني مؤكدان",
    "Wireframes approved": "الإطارات الأولية معتمدة",
    "High-fidelity designs completed": "التصاميم عالية الدقة مكتملة",
    "Architecture notes followed": "ملاحظات الهيكلة متبعة",
    "Code review approved": "مراجعة الكود معتمدة",
    "All comments resolved": "جميع التعليقات تم حلها",
    "All test cases executed": "جميع حالات الاختبار تم تنفيذها",
    "No open bugs": "لا أخطاء مفتوحة",
    "Regression tests passed": "اختبارات الانحدار نجحت",
    "Product owner sign-off": "موافقة مالك المنتج",
    "Release notes updated": "ملاحظات الإصدار محدثة",

    // Readiness checklist
    "Acceptance criteria defined": "معايير القبول محددة",
    "Business rules clear": "قواعد العمل واضحة",
    "Edge cases identified_checklist": "الحالات الحدية محددة",
    "Dependencies mapped": "التبعيات مرسومة",
    "Design available": "التصميم متاح",
    "API contract ready": "عقد API جاهز",
    "Estimation done": "التقدير تم",

    // Report recommendations
    "Introduce a daily async standup or structured check-in to close communication gaps across the team.": "تقديم اجتماع يومي غير متزامن أو تسجيل منظم لسد فجوات التواصل عبر الفريق.",
    "Prioritize blocker resolution in daily standups. Escalate blockers older than 2 days to leadership.": "إعطاء الأولوية لحل العوائق في الاجتماعات اليومية. تصعيد العوائق الأقدم من يومين للقيادة.",
    "Invest in a requirements review checklist and enforce it before any task enters development.": "الاستثمار في قائمة مراجعة المتطلبات وفرضها قبل دخول أي مهمة للتطوير.",
    "Assign a single clear owner to every task and shared component to eliminate duplicated effort.": "تعيين مالك واحد واضح لكل مهمة ومكون مشترك للقضاء على الجهد المكرر.",
    "Standardize handoff criteria between phases to reduce misunderstandings and rework.": "توحيد معايير التسليم بين المراحل لتقليل سوء الفهم وإعادة العمل.",
    "Review workload distribution to prevent burnout and improve delivery consistency.": "مراجعة توزيع عبء العمل لمنع الإرهاق وتحسين اتساق التسليم.",
    "Sprint completion is below 50%. Consider reducing scope or breaking tasks into smaller deliverables.": "إنجاز السبرنت أقل من 50%. فكر في تقليل النطاق أو تقسيم المهام إلى مخرجات أصغر.",
    "There are active blockers. Schedule a dedicated blocker-busting session to unblock the team.": "يوجد 5 عوائق نشطة. حدد جلسة مخصصة لإزالة العوائق لإلغاء حظر الفريق.",
    "The sprint is performing well across all areas. Continue current practices and focus on maintaining momentum.": "السبرنت يؤدي بشكل جيد في جميع المجالات. استمر في الممارسات الحالية وركز على الحفاظ على الزخم.",
    "The sprint is performing well across all areas. Continue current practices and look for incremental improvements.": "السبرنت يؤدي بشكل جيد في جميع المجالات. استمر في الممارسات الحالية وابحث عن تحسينات تدريجية.",

    // Friction area descriptions in reports
    "Requirements are well-defined. The team has clear acceptance criteria and minimal rework due to ambiguity.": "المتطلبات واضحة. الفريق لديه معايير قبول واضحة وإعادة عمل قليلة بسبب الغموض.",
    "Some requirements lack clarity. Occasional rework happens because acceptance criteria or edge cases are not fully defined before development starts.": "بعض المتطلبات تفتقر للوضوح. إعادة العمل تحدث أحياناً لأن معايير القبول أو الحالات الحدية غير محددة بالكامل قبل بدء التطوير.",
    "Requirements are frequently unclear or incomplete. The team is spending significant time on rework and clarification, slowing down delivery.": "المتطلبات غالباً غير واضحة أو غير مكتملة. الفريق يقضي وقتاً كبيراً في إعادة العمل والتوضيح، مما يبطئ التسليم.",
    "Team communication is strong. Information flows freely across roles, and decisions are shared promptly.": "تواصل الفريق قوي. المعلومات تتدفق بحرية عبر الأدوار والقرارات تُشارك بسرعة.",
    "Some communication gaps exist. Important updates occasionally get missed, leading to misalignment or duplicated work.": "بعض فجوات التواصل موجودة. التحديثات المهمة تُفقد أحياناً، مما يؤدي لعدم التوافق أو العمل المكرر.",
    "Communication is a major friction point. Critical information is not reaching the right people, causing delays and misunderstandings.": "التواصل نقطة احتكاك رئيسية. المعلومات الحرجة لا تصل للأشخاص المناسبين، مما يسبب تأخيرات وسوء فهم.",
    "Strong ownership culture. Team members take clear accountability for their tasks and follow through reliably.": "ثقافة ملكية قوية. أعضاء الفريق يتحملون مسؤولية واضحة عن مهامهم ويتابعونها بشكل موثوق.",
    "Ownership could improve. Some tasks lack a clear single owner, leading to ambiguity about who is responsible for driving them to completion.": "الملكية تحتاج تحسين. بعض المهام تفتقر لمالك واحد واضح، مما يؤدي لغموض حول من المسؤول عن إنجازها.",
    "Ownership is a significant problem. Many tasks are orphaned or have unclear ownership, resulting in dropped balls and slow progress.": "الملكية مشكلة كبيرة. كثير من المهام يتيمة أو ملكيتها غير واضحة، مما يؤدي لإسقاط المهام وبطء التقدم.",
    "Dependencies are well-managed. Blockers are rare and resolved quickly when they occur.": "التبعيات تُدار بشكل جيد. العوائق نادرة وتُحل بسرعة عند حدوثها.",
    "Some dependency issues are causing delays. A few blockers are taking longer than expected to resolve.": "بعض مشاكل التبعيات تسبب تأخيرات. بعض العوائق تستغرق وقتاً أطول من المتوقع لحلها.",
    "Dependencies are severely impacting delivery. Multiple long-standing blockers are preventing the team from making progress on critical work.": "التبعيات تؤثر بشدة على التسليم. عوائق متعددة طويلة الأمد تمنع الفريق من التقدم في العمل الحرج.",
    "Processes are mature and effective. Handoffs are smooth and the team follows consistent workflows.": "العمليات ناضجة وفعالة. التسليمات سلسة والفريق يتبع سير عمل متسق.",
    "Some process gaps exist. Handoffs between phases are not always smooth, causing delays in the pipeline.": "بعض فجوات العمليات موجودة. التسليمات بين المراحل ليست سلسة دائماً، مما يسبب تأخيرات في خط الإنتاج.",
    "Processes need significant improvement. Handoffs are frequently incomplete or delayed, and there is no consistent workflow the team follows.": "العمليات تحتاج تحسيناً كبيراً. التسليمات غالباً غير مكتملة أو متأخرة، ولا يوجد سير عمل متسق يتبعه الفريق.",
    "Team dynamics are excellent. Members are engaged, workload is balanced, and there is a healthy culture of collaboration and accountability.": "ديناميكيات الفريق ممتازة. الأعضاء منخرطون وعبء العمل متوازن وهناك ثقافة صحية من التعاون والمساءلة.",
    "Team dynamics are adequate but could improve. Some workload imbalances or decision-making delays are visible.": "ديناميكيات الفريق كافية لكن تحتاج تحسين. بعض اختلالات عبء العمل أو تأخيرات اتخاذ القرار مرئية.",
    "Team dynamics need attention. Significant workload imbalances, slow decision-making, or low engagement are impacting delivery.": "ديناميكيات الفريق تحتاج اهتمام. اختلالات كبيرة في عبء العمل أو بطء اتخاذ القرار أو انخفاض المشاركة تؤثر على التسليم.",
    // Report-specific recommendation strings
    "Invest in a requirements review checklist before sprint planning to reduce rework and improve task readiness.": "الاستثمار في قائمة مراجعة المتطلبات قبل تخطيط السبرنت لتقليل إعادة العمل وتحسين جاهزية المهام.",
    "Assign a single clear owner to every task and blocker. Consider a RACI matrix for cross-functional work.": "تعيين مالك واحد واضح لكل مهمة وعائق. فكر في مصفوفة RACI للعمل متعدد الوظائف.",
    "Standardize handoff criteria between phases. Create definition-of-done checklists for each transition.": "توحيد معايير التسليم بين المراحل. إنشاء قوائم تعريف الإنجاز لكل انتقال.",
    "Review workload distribution to prevent burnout. Ensure decisions are documented and shared transparently.": "مراجعة توزيع عبء العمل لمنع الإرهاق. ضمان توثيق القرارات ومشاركتها بشفافية.",
};

export const td = (text: string): string => {
    if (getLang() === "en") return text;
    return ar[text] ?? text;
};
